### ISSUE TITLE
Please update for actual libmdbx

### ISSUE THREAD

**Issue by erthink** [castortech/mdbxjni#3]
[libmdbx](https://github.com/erthink/libmdbx) have notable progress since last year.
So please update/sync your project.

**Comment by castortech** [comment]
Hi,

As we're approaching the 1 year anniversary of your message :) I finally
updated mdbxjni to the current version, covering (at least in the JNI
portion) all of the published API. Also a lot of Java accessors have been
updated as well.

So we are about ready to move from a spring 2018 version to the current
latest and greatest as we start to test our application with the new
version.

I must say that I noticed the deprecation of the key comparators and read
the related issue. I think it is a good idea to make it "discouraged" in
general, but deprecated frightens me. We use (for keys, not data) custom
comparators all the time. Initially we could probably have used the built
in comparators, but our API that sits on top supports custom comparators.
More importantly IMHO is that we now have special wrapper comparators to
support field level encryption and those wrap the base comparator.

I would feel better to provide our custom utilities, even in java for us,
or implement the comparators in C but retain control of the
encryption/decryption and the key selection logic (we support multi-tenancy
with tenant specific keys).

Cheers,
Alain

Alain Picard
Chief Strategy Officer
Castor Technologies Inc
o:514-360-7208
m:813-787-3424

***@***.***
www.castortech.com

**Comment by castortech** [comment]
This has now been done and the current version is in sync with libmdbx
