### ISSUE TITLE
how can import dependency jar?

### ISSUE THREAD

**Issue by xtuyaowu** [castortech/mdbxjni#7]
hi add flowing into pom dose not work thanks for answer!

<dependencies>
  <dependency>
    <groupId>org.fusesource.lmdbjni</groupId>
    <artifactId>mdbxjni-all</artifactId>
    <version>99-master-SNAPSHOT</version>
  </dependency>
</dependencies>
...
<repositories>
    <repository>
      <id>fusesource.nexus.snapshot</id>
      <name>FuseSource Community Snapshot Repository</name>
      <url>http://repo.fusesource.com/nexus/content/groups/public-snapshots</url>
    </repository>
</repositories>

**Comment by castortech** [comment]
I will look into it

**Comment by xtuyaowu** [comment]
please give an mdbxjni-all.jar

**Comment by castortech** [comment]
I added a basic [release](https://github.com/castortech/mdbxjni/releases/tag/v0.11.1), that is not the all uber jar but does contain everything for Linux or Windows.

**Comment by xtuyaowu** [comment]
thanks, i have to wait for the next version , beacuse my os is mac!

**Comment by xtuyaowu** [comment]
hi  castortech can provide jar for mac? thanks

**Comment by castortech** [comment]
> hi castortech can provide jar for mac? thanks

New release that includes Mac OS X is now available

**Comment by xtuyaowu** [comment]
thanks !
